version: '3.8'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command:
      redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    tty: true
  tests:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TESTING=1
    command: [ "poetry", "run", "pytest", "-v" ]
    depends_on:
      - redis
    tty: true
volumes:
  redis_data: